apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: devfile-sample-belz
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: devfile-sample-belz
    app.kubernetes.io/part-of: ci1t-43256-0084-app
  name: devfile-sample-belz
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: nodejs-app
      app.kubernetes.io/instance: devfile-sample-belz
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: nodejs-app
        app.kubernetes.io/instance: devfile-sample-belz
    spec:
      containers:
      - image: quay.io/stonesoup_perfscale/ci1t-43256-0084-tenant/ci1t-43256-0084-app/devfile-sample-belz@sha256:b9f54277717a287a56310a22c21a201f24eeeefc874e0f1ee09df32e5b848032
        name: my-nodejs
        ports:
        - containerPort: 3001
          name: http
          protocol: TCP
        resources:
          requests:
            cpu: 10m
            memory: 50Mi
status: {}
